"""
Phase 4 tests: PDF parsing, tables, images, scanned-page detection, OCR and
layout classification, using PDFs generated by tests/pdf_factory.py.

OCR tests need the `tesseract` binary and are skipped where it is missing
(it is installed in the worker image and in CI).
"""

import shutil

import pytest

from app.document_processing.layout import is_heading
from app.document_processing.ocr import words_to_blocks
from app.document_processing.parser import (
    BlockKind,
    CorruptPdfError,
    EncryptedPdfError,
    ParsedDocument,
    Table,
    TextBlock,
    TextSource,
    TooManyPagesError,
)
from app.document_processing.pymupdf_parser import _join_lines, is_scanned_page, open_pdf
from app.document_processing.tables import clean_rows, is_real_table
from app.services.ocr_service import ocr_scanned_pages
from app.services.pdf_service import PdfOptions, extraction_summary, finalize_layout, parse_pdf
from tests import pdf_factory

needs_tesseract = pytest.mark.skipif(
    shutil.which("tesseract") is None, reason="tesseract binary not installed"
)
OPTIONS = PdfOptions()


@pytest.fixture(scope="module")
def contract():
    """Parsed + layout-classified 3-page contract, shared by several tests."""
    result = parse_pdf(pdf_factory.contract_pdf(), OPTIONS)
    finalize_layout(result.document)
    return result


def _kinds(page) -> dict[str, BlockKind]:
    return {b.text: b.kind for b in page.blocks}


# --- Opening files -------------------------------------------------------------------


def test_corrupt_file_is_a_permanent_error():
    with pytest.raises(CorruptPdfError):
        open_pdf(b"%PDF-1.7 this is not really a pdf")


def test_password_protected_pdf_is_rejected_with_user_message():
    with pytest.raises(EncryptedPdfError, match="password-protected"):
        parse_pdf(pdf_factory.encrypted_pdf(), OPTIONS)


def test_owner_password_only_pdf_is_processed():
    # Only printing/copying is restricted; anyone can open and read it.
    result = parse_pdf(pdf_factory.encrypted_pdf(user_password=""), OPTIONS)
    assert "Secret terms" in result.document.pages[0].blocks[0].text


def test_page_limit_is_checked_before_reading():
    with pytest.raises(TooManyPagesError, match="limit is 2"):
        parse_pdf(pdf_factory.contract_pdf(pages=3), PdfOptions(max_pages=2))


# --- Text layer, tables, images --------------------------------------------------------


def test_digital_contract_text_tables_images_metadata(contract):
    doc = contract.document
    assert doc.page_count == 3 and doc.scanned_page_numbers == []
    assert doc.metadata["title"] == "MSA - Acme"

    tables = doc.pages[1].tables
    assert len(tables) == 1
    assert tables[0].rows == pdf_factory.TABLE

    assert len(contract.images) == 1
    image = contract.images[0]
    assert image.page_number == 3 and image.png.startswith(b"\x89PNG")
    assert (image.image.width_px, image.image.height_px) == (300, 200)


def test_layout_labels_headings_lists_headers_footers_and_table_text(contract):
    page1, page2, _ = contract.document.pages
    kinds1 = _kinds(page1)
    assert kinds1[pdf_factory.TITLE] is BlockKind.HEADING
    assert kinds1["1. DEFINITIONS"] is BlockKind.HEADING
    assert kinds1[pdf_factory.HEADER] is BlockKind.HEADER
    assert kinds1["Page 1 of 3"] is BlockKind.FOOTER
    assert kinds1[pdf_factory.BODY] is BlockKind.PARAGRAPH
    assert any(k is BlockKind.LIST_ITEM for t, k in kinds1.items() if t.startswith("(a)"))

    kinds2 = _kinds(page2)
    assert kinds2["8.3 Notice Period"] is BlockKind.HEADING
    assert any(k is BlockKind.TABLE_TEXT for k in kinds2.values())

    # Readable text excludes running headers/footers and duplicated table cells.
    assert pdf_factory.HEADER not in page1.text and "Page 1 of 3" not in page1.text
    assert "Kick-off" not in page2.text
    assert pdf_factory.BODY in page2.text


def test_parsed_document_survives_json_roundtrip(contract):
    data = contract.document.to_dict()
    restored = ParsedDocument.from_dict(data)
    assert restored.to_dict() == data
    assert restored.pages[1].tables[0].rows == pdf_factory.TABLE


def test_extraction_summary_records_counts_and_engine_versions(contract):
    summary = extraction_summary(contract.document, image_count=1, warnings=[])
    assert summary["pages"] == 3 and summary["tables"] == 1 and summary["images"] == 1
    assert summary["engines"]["pymupdf"] and summary["engines"]["pdfplumber"]


# --- Scanned pages & OCR -----------------------------------------------------------------


def test_scanned_page_is_detected_and_not_exported_as_an_image():
    result = parse_pdf(pdf_factory.scanned_pdf(), OPTIONS)
    page = result.document.pages[0]
    assert page.is_scanned and page.blocks == [] and page.tables == []
    assert result.images == []  # its content comes from OCR, not a stored picture


@pytest.mark.parametrize(
    ("chars", "coverage", "scanned"),
    [(0, 1.0, True), (10, 0.9, True), (0, 0.0, False), (500, 1.0, False), (10, 0.3, False)],
)
def test_scanned_page_rule(chars, coverage, scanned):
    # blank page (0, 0.0) and searchable scan (500, 1.0) are NOT scanned
    assert is_scanned_page(chars, coverage) is scanned


@needs_tesseract
def test_ocr_reads_scanned_page_and_layout_finds_heading():
    data = pdf_factory.scanned_pdf()
    result = parse_pdf(data, OPTIONS)
    warnings = ocr_scanned_pages(data, result.document, OPTIONS)
    finalize_layout(result.document)

    page = result.document.pages[0]
    assert warnings == []
    assert page.ocr_confidence and page.ocr_confidence > 60
    assert all(b.source is TextSource.OCR for b in page.blocks)
    assert "terminate this Agreement" in page.text
    headings = [b.text for b in page.blocks if b.kind is BlockKind.HEADING]
    assert "TERMINATION" in headings


def test_ocr_disabled_leaves_a_warning_instead_of_failing():
    data = pdf_factory.scanned_pdf()
    result = parse_pdf(data, OPTIONS)
    warnings = ocr_scanned_pages(data, result.document, PdfOptions(ocr_enabled=False))
    assert warnings and "OCR is disabled" in warnings[0]


def test_ocr_words_grouped_into_paragraphs_in_pdf_points():
    # Two words in paragraph (1,1), one in (2,1), plus a structural row (conf -1).
    data = {
        "text": ["", "Notice", "period", "Fees"],
        "conf": ["-1", "90", "80", "70"],
        "block_num": [1, 1, 1, 2],
        "par_num": [0, 1, 1, 1],
        "left": [0, 300, 600, 300],
        "top": [0, 300, 300, 900],
        "width": [0, 250, 300, 200],
        "height": [0, 50, 50, 50],
    }
    result = words_to_blocks(data, scale=72 / 300)
    assert [b.text for b in result.blocks] == ["Notice period", "Fees"]
    assert result.blocks[0].bbox == (72.0, 72.0, 216.0, 84.0)  # 300px @300dpi = 1in = 72pt
    assert result.blocks[0].confidence == 85.0
    assert result.mean_confidence == 80.0


# --- Small helpers ---------------------------------------------------------------------


@pytest.mark.parametrize(
    ("text", "bold", "expected"),
    [
        ("8.3 Notice Period", False, True),  # numbered + title case
        ("ARTICLE 5", False, True),
        ("TERMINATION", False, True),  # all caps (typical OCR heading)
        ("8.3 The Supplier shall pay all invoices", False, False),  # a clause sentence
        ("Definitions", True, True),  # bold short line
        ("This Agreement is governed by English law.", True, False),  # ends like a sentence
        ("word " * 30, True, False),  # too long
    ],
)
def test_heading_rules(text, bold, expected):
    block = TextBlock(text=text, bbox=(0, 0, 1, 1), font_size=10, is_bold=bold)
    assert is_heading(block, body_size=10) is expected


def test_wrapped_lines_are_joined_and_hyphenation_repaired():
    assert _join_lines(["Either party may termi-", "nate this", "  Agreement."]) == (
        "Either party may terminate this Agreement."
    )


def test_table_cleanup_and_markdown():
    rows = clean_rows([["Fee", None, "Due\ndate"], [None, None, None], ["10|000", None, "Q1"]])
    assert rows == [["Fee", "Due date"], ["10|000", "Q1"]]
    assert is_real_table(rows) and not is_real_table([["only one cell"]])
    md = Table(bbox=(0, 0, 1, 1), rows=rows).to_markdown()
    assert md.splitlines() == ["| Fee | Due date |", "| --- | --- |", "| 10\\|000 | Q1 |"]
